### PR TITLE
Switch to Postmark for email delivery

### LINKED ISSUE #462: Batch invitation to anthology issue
It sounds like the invite to anthology feature is not working as expected. I believe it's supposed to send emails to all invited students, and it does not, at least on the Purdue tenant. Not sure whether emails are being sent but blocked, or not sent.

### PR DESCRIPTION
**Pull request by camdendotlol**
# Summary

- switches from using Sendgrid via SMTP to Postmark via the official `postmark-rails` gem, which uses the Postmark API

Using the Postmark API rather than SMTP will provide more clarity if/when email delivery issues occur in the future.

Closes #462 

# To do

We still need to add covecollective.org as an authorized sender on Postmark.

# Testing

1. Go to the staging site (let me know first so I can deploy this branch to staging)
2. Invite some users to an anthology with email addresses that link to your Performant email using the `+` trick
3. The invitation emails should arrive in your inbox

### CODE REVIEW

**Comment by camdendotlol** [comment]
@jamiefolsom This has passed Steve's testing, but we still need `info@covecollective.org` to be added to the verified senders list. As far as I can tell, I don't have the permissions required to do that in Postmark.

File: config/environments/development.rb [hunk 1]
```diff
@@ -45,19 +45,13 @@
...
+  config.action_mailer.delivery_method = :postmark
+  config.action_mailer.postmark_settings = { :api_token => ENV['POSTMARK_TOKEN'] }
+
+  config.action_mailer.raise_delivery_errors = true
   config.action_mailer.default_url_options = { :host => 'localhost:3000' }
   config.action_mailer.perform_deliveries = true
-  config.action_mailer.delivery_method = :smtp
   config.action_mailer.default :charset => "utf-8"  
-  config.action_mailer.smtp_settings =  {
-    :address  => "smtp.postmarkapp.com",
```
Comment (jamiefolsom) [inline config/environments/development.rb:53]: Was postmark SMTP config already in place, so this is just a switch to using their API?

File: config/environments/production.rb [hunk 2]
```diff
@@ -70,18 +70,10 @@
   config.active_support.deprecation = :notify
 
   config.action_mailer.default_url_options = { :host => ENV['EMAIL_DOMAIN'] }
+  config.action_mailer.postmark_settings = { :api_token => ENV['POSTMARK_TOKEN'] }
   config.action_mailer.perform_deliveries = true
-  config.action_mailer.delivery_method = :smtp
+  config.action_mailer.delivery_method = :postmark
   config.action_mailer.default :charset => "utf-8"
-  config.action_mailer.smtp_settings = {
```
Comment (jamiefolsom) [inline config/environments/production.rb:76]: Ah, looks like we were using Sendgrid.

**Review by jamiefolsom — APPROVED** [review]
One question, which I answered for myself. Looks good!

File: config/environments/development.rb (hunk 1 above)
Comment (camdendotlol) [reply config/environments/development.rb:53]: We were using Postmark for local development builds. I switched to the Postmark API partly because they strongly encourage it and partly because it seems to be better at logging errors.
